void displayValues(maillon *ptrtete);
maillon *createMaillon(arith *data);
maillon *lastMaillon(maillon *ptrtete, arith *data);
void insertMaillon(maillon *new, maillon **ptrtete);
void insertValue(maillon **ptrtete, arith *data);
maillon *createList();
maillon *seekingMaillon(maillon *ptrtete, arith *data);
void deleteMaillon(maillon **ptrtete,maillon *delete);
maillon *deleteValue(maillon **ptrtete,arith *data);
void deleteList(maillon **ptrtete);
void invertList(maillon **ptrtete);
